
development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url:     redis://redistogo:192csd9c30ca49585ce9d85daf0fer90@tarpon.redistogo.com:49382
  :host: tarpon.redistogo.com
  :port: 49382
  :password: 349f93483fv9erfv849dfvdfbds9
  :inline: true
  :timeout: 1
